const accountsData = [
  {
    id: '1',
    profileId: 'kkg5f1b',
    email: 'lorn.daily0n@icloud.com',
    password: 'gW25%23yE36k',
  },
  {
    id: '2',
    profileId: 'kkg5f1c',
    email: 'tug01.yard@icloud.com',
    password: 'eY42^3@qtNsK',
  },
  {
    id: '3',
    profileId: 'kkg5f1d',
    email: 'hills-mediate.01@icloud.com',
    password: 'uWu28#-QjgnW72@n',
  },
  {
    id: '4',
    profileId: 'kkg5f1e',
    email: 'taste-07.lining@icloud.com',
    password: 'gEW5@16^34rt',
  },
  {
    id: '5',
    profileId: 'kkg5f1f',
    email: 'peach_smiles.0k@icloud.com',
    password: 'pAo8#8^92jW2!',
  },
  {
    id: '6',
    profileId: 'kkg5f1g',
    email: 'dilute.serials_0p@icloud.com',
    password: 'j#5iflsWo$@5',
  },
  {
    id: '7',
    profileId: 'kkg5f1h',
    email: 'binding.tasty-0n@icloud.com',
    password: 'jAp3(03@6$j',
  },
  {
    id: '8',
    profileId: 'kkg5f1i',
    email: 'devious_house0i@icloud.com',
    password: 'iE3(34%JSMaL32',
  },
  {
    id: '9',
    profileId: 'kkg5f1j',
    email: 'servant-scurf.0l@icloud.com',
    password: 'xXui29#2&fkWo#',
  },
  {
    id: '10',
    profileId: 'kkg5f1k',
    email: 'bagpipe-agree0l@icloud.com',
    password: 'zgfkHGmnhjg3798(^&)(%)',
  },
  {
    id: '11',
    profileId: 'kkg5f1l',
    email: 'calcite-stucco-0e@icloud.com',
    password: 'vgh98^*GVBSTy3%',
  },
  {
    id: '12',
    profileId: 'kkg5f1m',
    email: 'mantrap_nuance06@icloud.com',
    password: '98hkiRFD%$(*#*)KYgyrY',
  },
  {
    id: '13',
    profileId: 'kkg5f1n',
    email: 'kiddy.slicer.0w@icloud.com',
    password: '987UHOKJhg#@!HYg*',
  },
  {
    id: '14',
    profileId: 'kkg5f1o',
    email: 'hazels-prelims.0q@icloud.com',
    password: 'uhfg(*$%HFHGtyrf87',
  },
  {
    id: '15',
    profileId: 'kkg5f1p',
    email: 'city.molts-0q@icloud.com',
    password: '98hhhh$HRJK8H%kh&',
  },
  {
    id: '16',
    profileId: 'kkg5f1r',
    email: 'pistil-upsilon0l@icloud.com',
    password: ':HJekuds75#)!*%(j',
  },
  {
    id: '17',
    profileId: 'kkg5f1s',
    email: '07.melanin_agar@icloud.com',
    password: '09klehkGEDRiI#%k&',
  },
  {
    id: '18',
    profileId: 'kkg5f1t',
    email: 'pen_fetal0v@icloud.com',
    password: 'asearuLJH@(&%^KMJH4oj3',
  },
  {
    id: '19',
    profileId: 'kkg5f1u',
    email: 'earths_defeat.0e@icloud.com',
    password: 'IUHGEW*74kjd^(*)',
  },
  {
    id: '20',
    profileId: 'kkg5f1v',
    email: 'auteur-erasure-04@icloud.com',
    password: 'fiYT&%$#',
  },
  {
    id: '21',
    profileId: 'kkg5f1w',
    email: 'driven_flanks_0v@icloud.com',
    password: 'i987)*(HK3gK7r54HY^&',
  },
  {
    id: '22',
    profileId: 'kkg5f1x',
    email: 'waiting_medleys_0z@icloud.com',
    password: 'h=-PUI8@kijgGFIKOlj',
  },
  {
    id: '23',
    profileId: 'kkg5f1y',
    email: 'mussel_snubs.0x@icloud.com',
    password: '09poioJUTG2#I&^%$Ggsa3',
  },
  {
    id: '24',
    profileId: 'kkg5f20',
    email: 'dip.acclaim0j@icloud.com',
    password: 'FYtyh^%$%#$&*iuug635%&*',
  },
  {
    id: '25',
    profileId: 'kkg5f21',
    email: 'agape_03_prize@icloud.com',
    password: 'srekju@$:OIGJHP:O',
  },
  {
    id: '26',
    profileId: 'kkg5f22',
    email: 'stable-newt0d@icloud.com',
    password: 'jhuDjWS6w*wjdMKw$#q',
  },
  {
    id: '27',
    profileId: 'kkg5f23',
    email: 'vocal_peeks0n@icloud.com',
    password: 'GHKkjfiu*3uhgjJIre8%',
  },
  {
    id: '28',
    profileId: 'kkg5f24',
    email: 'almond.assents0g@icloud.com',
    password: 'HJFiuIF**g*gYsKJNRAGYKjhL',
  },
  {
    id: '29',
    profileId: 'kkg5f25',
    email: 'watcher00lentils@icloud.com',
    password: 'iu676GUjiR53R4Yh&',
  },
  {
    id: '48',
    profileId: 'kkg5f2p',
    email: 'hefts.screech-0q@icloud.com',
    password: '987^$#hgf%DFhgdf3*(h&',
  },
  {
    id: '49',
    profileId: 'kkg5f2q',
    email: 'jacks.ripped.0f@icloud.com',
    password: ')(ikhjggf4548HGFfd3*&^gvu$fd5',
  },
  {
    id: '50',
    profileId: 'kkg5f2r',
    email: 'burger-dinners0k@icloud.com',
    password: 'kjh8H^&%jhgfhg654v#',
  },
];

export default accountsData;
