services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - /backend/.env
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

networks:
  app-network:
