name: 'crydonkey-${ENVIRONMENT}'

services:
  server:
    container_name: crydonkey-server-${ENVIRONMENT}
    build:
      context: .
      target: ${ENVIRONMENT}
    image: crydonkey-server:${ENVIRONMENT}
    ports:
      - "${EXPRESS_SERVER_PORT}:${EXPRESS_SERVER_PORT}"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - crydonkey-network

  redis:
    image: redis:alpine
    container_name: crydonkey-redis-${ENVIRONMENT}
    ports:
      - "${REDIS_PORT_LOCAL}:${REDIS_PORT}"
    volumes:
      - ${REDIS_DATA_PATH}:/data/redis
    networks:
      crydonkey-network:
        aliases:
          - redis

  mongo:
    image: mongo:latest
    container_name: crydonkey-mongo-${ENVIRONMENT}
    command: [ "mongod", "--config", "/etc/mongod.conf" ]
    ports:
      - "${DB_PORT_LOCAL}:${DB_PORT}"
    volumes:
      - ${DB_DATA_PATH}:/data/db
      - ./src/db/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./mongod.conf:/etc/mongod.conf:ro
    networks:
      crydonkey-network:
        aliases:
          - mongo

networks:
  crydonkey-network:
    driver: bridge
