services:
  server:
    container_name: crydonkey-server
    build:
      context: .
      target: ${ENVIRONMENT}
    image: crydonkey-server:${ENVIRONMENT}
    ports:
      - "${EXPRESS_SERVER_PORT}:${EXPRESS_SERVER_PORT}"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - crydonkey-network

  redis:
    image: redis:alpine
    container_name: crydonkey-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ${REDIS_DATA_PATH}:/data/redis
    networks:
      - crydonkey-network

  mongo:
    image: mongo:latest
    container_name: crydonkey-mongo
    restart: always
    command: [ "mongod", "--config", "/etc/mongod.conf" ]
    ports:
      - "${DB_PORT_LOCAL}:${DB_PORT}"
    volumes:
      - ${DB_DATA_PATH}:/data/db
      - ./src/db/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./mongod.conf:/etc/mongod.conf:ro
    networks:
      - crydonkey-network

networks:
  crydonkey-network:
    driver: bridge
